// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamUpdateBot.Persistence;

#nullable disable

namespace SteamUpdateBot.Persistence.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260816182313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SteamUpdateBot.Core.Domain.AnnouncementRecord", b =>
                {
                    b.Property<long>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamGid")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeliveredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DetectedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordMessageId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("NextAttemptUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PublishedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("AppId", "SteamGid");

                    b.HasIndex("DeliveryState", "NextAttemptUtc", "PublishedAtUtc");

                    b.ToTable("Announcements", (string)null);
                });

            modelBuilder.Entity("SteamUpdateBot.Core.Domain.MonitoredGame", b =>
                {
                    b.Property<long>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddedByDiscordUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeaderImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastPollAttemptUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastPollSuccessUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("NextPollUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScanWatermarkUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("AppId");

                    b.HasIndex("NextPollUtc");

                    b.ToTable("MonitoredGames", (string)null);
                });

            modelBuilder.Entity("SteamUpdateBot.Core.Domain.AnnouncementRecord", b =>
                {
                    b.HasOne("SteamUpdateBot.Core.Domain.MonitoredGame", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
