<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SteamUpdateBot.Core/SteamUpdateBot.Core.csproj" />
    <ProjectReference Include="../../src/SteamUpdateBot.Steam/SteamUpdateBot.Steam.csproj" />
    <ProjectReference Include="../../src/SteamUpdateBot.Persistence/SteamUpdateBot.Persistence.csproj" />
    <ProjectReference Include="../../src/SteamUpdateBot.App/SteamUpdateBot.App.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
</Project>
